---
nav:
  - Home: index.md
  - Access & Usage: 
      - Cloud Access (Virtual Machines):
          - TalTech OpenStack Cloud: access/cloud.md
      - TalTech Cluster (Compute Resources): 
          - Cluster usage: access/cluster.md
          - MPI: access/mpi.md
          - SAMBA Network Drive: access/samba.md
          - Cluster GPU usage: access/cluster-gpu.md
          - Cluster Hardware: access/hardware.md
      - LUMI (Compute Resources): 
          - What is and why to use LUMI?: access/lumi.md
          - Quick Start: access/lumi-start.md
          - Software: access/lumi-software.md
          - Slurm Usage Examples: access/lumi-examples.md
      - Access:
        - Putty: access/putty.md
        - SSH Key Generation: access/ssh.md
  - Learning:
      - learning/learning.md
      - Performance: learning/performance.md
      - Profiling: learning/profiling.md
  - Job Submission:
      - Slurm Examples: jobs/slurm-example.md
      - Slurm Statistics: jobs/slurm-statistics.md
      - Singularity Containers: jobs/singularity.md
  - Software:
      - software/software.md
      - Modules and Package Managers:
          - Modules: software/modules.md
          - EasyBuild: software/easybuild.md
          - SPACK: software/spack.md
      - Engineering Software:
          - CAD-Mesh: software/cad-mesh.md
          - ElmerFEM: software/elmerfem.md
          - OpenFOAM: software/openfoam.md
          - SWAN: software/swan.md
          - WAM: software/wam.md
      - Chemistry Software:
          - xtb-CREST: software/crest.md
          - Gaussian: software/gaussian.md
          - ORCA: software/orca.md
          - NWChem: software/nwchem.md
          - Multiwfn: software/multiwfn.md
          - XTB: software/xtb.md
          - TURBOMOLE: software/turbomole.md
          - Chemistry Visualization: visualization/visualization-chemistry.md
      - Data Analysis Software:
          - Jupyter: software/jupyter.md
          - Octave: software/octave.md
      - Other:
          - Computational Fluid Dynamics: software/cfd.md
          - Finite Element Analysis: software/fea.md
          - Chapel: software/chapel.md
          - Define: software/define.md
          - cp2k: software/cp2k.md

  - Visualization:
      - visualization/visualization.md
      - VNC: visualization/vnc.md
      - X2Go: visualization/x2go.md
      - Xpra: visualization/xpra.md
      - VirtualGL: visualization/VirtualGL.md
      - Chemistry Visualization: visualization/visualization-chemistry.md
  - Acknowledgement: acknowledgement.md


site_name: TalTech HPC User Guides
site_author: TalTech HPC
site_url: https://taltech-hpc-centre.github.io/taltech-hpc-docs/
edit_uri: https://github.com/TalTech-HPC-Centre/taltech-hpc-docs/edit/master/docs/
docs_dir: docs
repo_name: github.com/TalTech-HPC-Centre
#repo_url: https://github.com/TalTech-HPC-Centre/taltech-hpc-docs
validation:
  links:
    absolute_links: relative_to_docs

theme:
  name: material
  #custom_dir: docs/overrides
  language: en
  favicon: assets/favicon.ico
  logo: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - header.autohide
    #- navigation.expand
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tabs.sticky
    - content.tabs.link
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.action.view
    - navigation.indexes
    - navigation.prune
    #- toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: "Noto Sans"
    code: "Roboto Mono"

plugins:
  - search
  - glightbox
#  - exporter
#  - exporter-pdf
#  - exporter-extras:
#      buttons:
#        - title: Download as PDF
#          icon: material-file-download-outline
#          enabled: !!python/name:mkdocs_exporter.plugins.pdf.button.enabled
#          attributes:
#            href: !!python/name:mkdocs_exporter.plugins.pdf.button.href
#            download: !!python/name:mkdocs_exporter.plugins.pdf.button.download
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

markdown_extensions:
  - def_list
  - admonition
  - meta
  - md_in_html
  - attr_list
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: false
      linenums_style: table
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      title: On this page
      permalink: "#"
      permalink_title: Anchor link to this section for reference
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/solid/house
      link: https://hpc.taltech.ee/
    - icon: fontawesome/brands/github
      link: https://github.com/TalTech-HPC-Centre
    - icon: fontawesome/solid/envelope
      link: mailto:hpcsupport@taltech.ee
    - icon: fontawesome/solid/comments
      link: https://taltech.atlassian.net/servicedesk/customer/portal/18/create/228
